// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Grayspace
{
    using ExprObjModel;
    using System.Collections.Generic;
    using System.Configuration;
    using System;
    
    
    #line 1 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class PreTextTemplate1 : PreTextTemplate1Base
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<title>");
            
            #line 8 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("</title>\r\n</head>\r\n<body>\r\n<h1>");
            
            #line 11 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n<pre>\r\n");
            
            #line 13 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"

SchemeScanner s = new SchemeScanner();
int grayArea = 0;
int lineNumber = 1;
foreach(string line in SchemeLines)
{
    s.ResetMode();
    int nextGrayArea = grayArea;
    GrayPrint(LexemeType.Whitespace, lineNumber.ToString("000000") + "  ", 8 + 2 * grayArea);
    int grayRemain = 2 * grayArea;
    foreach(ScanResult sr in Scan(s, line))
    {
        nextGrayArea += Change(sr.type);
        GrayPrint(sr.type, sr.str, grayRemain);
        grayRemain -= sr.str.Length;
    }
    WriteLine("");
    grayArea = nextGrayArea;
    ++lineNumber;
}

            
            #line default
            #line hidden
            this.Write("</pre>\r\n</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 37 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"

public string Title { get; set; }

public IEnumerable<string> SchemeLines { get; set; }

public IEnumerable<ScanResult> Scan(SchemeScanner ss, string line)
{
    int pos = 0;
    int newPos;
    ScanResult sr = default(ScanResult);
    while(true)
    {
        ss.Scan(line, pos, out sr, out newPos);
        yield return sr;
        if (newPos == line.Length) break;
        pos = newPos;
    }
}

public string GetForeColor(LexemeType lt)
{
    string name = lt.ToString() + "_F";
    return ConfigurationManager.AppSettings[name] ?? "#000000";
}

public string GetBackColor(LexemeType lt)
{
    string name = lt.ToString() + "_B";
    return ConfigurationManager.AppSettings[name] ?? "#FFFFFF";
}

public string GetGrayForeColor(LexemeType lt)
{
    string name = lt.ToString() + "_GF";
    return ConfigurationManager.AppSettings[name] ?? GetForeColor(lt);
}

public string GetGrayBackColor(LexemeType lt)
{
    string name = lt.ToString() + "_GB";
    return ConfigurationManager.AppSettings[name] ?? "#D0D0D0";
}

public int Change(LexemeType lt)
{
    switch(lt)
    {
        case LexemeType.LeftParen:
        case LexemeType.PoundLeftParen:
        case LexemeType.PoundSLeftParen:
        case LexemeType.PoundMLeftParen:
        case LexemeType.PoundSigLeftParen:
        case LexemeType.PoundMsgLeftParen:
        case LexemeType.PoundVector3LeftParen:
        case LexemeType.PoundVertex3LeftParen:
        case LexemeType.PoundVector2LeftParen:
        case LexemeType.PoundVertex2LeftParen:
        case LexemeType.PoundQuatLeftParen:
            return 1;
        case LexemeType.RightParen:
            return -1;
        default:
            return 0;
    }
}

public void GrayPrint(LexemeType lt, string str, int grayChars)
{
    if (str.Length == 0) return;
    if (grayChars > 0)
    {
        string fg = GetGrayForeColor(lt);
        string bg = GetGrayBackColor(lt);
        
        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("<span style=\"color: ");

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fg));

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("; background-color: ");

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(bg));

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("\">");

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(((grayChars < str.Length) ? str.Substring(0, grayChars) : str)));

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("</span>");

        
        #line default
        #line hidden
        
        #line 110 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"

    }
    if ((str.Length - grayChars) > 0)
    {
        string fg = GetForeColor(lt);
        string bg = GetBackColor(lt);
        
        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("<span style=\"color: ");

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fg));

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("; background-color: ");

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(bg));

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(";\">");

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(((grayChars < 0) ? str : str.Substring(grayChars))));

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"
this.Write("</span>");

        
        #line default
        #line hidden
        
        #line 116 "G:\Vapar\vs2010c\15\swscheme1\Grayspace\PreTextTemplate1.tt"

    }
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class PreTextTemplate1Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
