del SchemeConsole.exe
del SchemeConsole.pdb
del SchemeRun.exe
del SchemeRun.pdb
del ExprObjModel.dll
del ExprObjModel.pdb
del ControlledWindowLib.dll
del ControlledWindowLib.pdb
del swscheme2.xml
del swscheme2.xsl
del Grayspace.exe
del Grayspace.pdb
del Grayspace.exe.config
